services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./basil:/usr/src/basil
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: big_problem
      POSTGRES_DB: basil
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
